// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "BoulderIntake.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

BoulderIntake::BoulderIntake() : Subsystem("BoulderIntake") {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    intakeUpandDown = RobotMap::boulderIntakeintakeUpandDown;
    intakeBeltMotor = RobotMap::boulderIntakeintakeBeltMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    //limitBottom = RobotMap::boulderIntakelimitBottom;
}

void BoulderIntake::InitDefaultCommand() {
    // Set the default command for a subsystem here.
    // SetDefaultCommand(new MySpecialCommand());
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}

void BoulderIntake::IntakeUp(){

	intakeUpandDown->Set(-0.8);//sets the intake motor to go up


}

void BoulderIntake::StopIntake(){

	intakeUpandDown->Set(0.0);
	intakeBeltMotor->Set(0.0);
}

void BoulderIntake::down(){

	intakeUpandDown->Set(0.8);
	intakeBeltMotor->Set(1.0);

}

void BoulderIntake::belts(double speed){

	intakeBeltMotor->Set(speed);//runs the belts on the intake arm

}
