// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.



#include "LowBar.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

LowBar::LowBar() {
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
     // Add Commands here:
    // e.g. AddSequential(new Command1());
    //      AddSequential(new Command2());
    // these will run in order.
	AddSequential(new AutoIntakeDown());//brings intake down for lowbar
	AddSequential(new AutonomousDriveForward());//drives forward for 3 seconds
	AddSequential(new AutoIntakeWheels());//makes sure ball goes in if it fell back into the intake
	AddSequential(new AutoIntakeUp());//pulls intake up so robot can turn.
	AddSequential(new AutoTurn());//turns about 45 degrees

	AddSequential(new LongDistance());
	AddParallel(new AutoLaunch());//spins up the launcher while timer for flipper starts
	AddSequential(new AutoFlipperLaunch());//launches after 3 seconds
	// To run multiple commands at the same time,
    // use AddParallel()
    // e.g. AddParallel(new Command1());
    //      AddSequential(new Command2());
    // Command1 and Command2 will run in parallel.

    // A command group will require all of the subsystems that each member
    // would require.
    // e.g. if Command1 requires chassis, and Command2 requires arm,
    // a CommandGroup containing them would require both the chassis and the
    // arm.
              // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
                      // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
 }
